name: bloc_ease
description: A dart library to solve boilerplate issues with flutter_bloc by just using typedefs instead of defining state classes.
version: 1.1.1+1
repository: https://github.com/Bharathh-Raj/bloc_ease
issue_tracker: https://github.com/Bharathh-Raj/bloc_ease/issues
topics: [bloc, flutter-bloc, state-management]
funding: [https://www.buymeacoffee.com/bharath213]

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

screenshots:
  - description: The bloc_ease package logo.
    path: screenshots/bloc_ease.png